logging:
    level:
        blog: WARN
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor: TRACE
            nodeValue: WARN
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?${DATABASE_QSP}
        username: ${DATABASE_ROOT_USER}
        password: ${DATABASE_ROOT_PASS}
    #  servlet:
    #    multipart:
    #      max-file-size: 15MB
    #      max-request-size: 15MB
    jpa:
        hibernate:
            ddl-auto: update
            #//TODO: change ddl-auto when ready
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#    web:
#      resources:
#        static-locations: classpath:/static/
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

server:
    port: ${APP_PORT}

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

database:
    admin-username: ${DATABASE_ADMIN_USER}
    admin-password: ${DATABASE_ADMIN_PASS}