logging:
    level:
        blog: WARN
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor: TRACE
            nodeValue: WARN
#            springframework:
#                security:
#                    web:
#                        FilterChainProxy=DEBUG:

spring:
    datasource:
        #       This is for Heroku Cloud
        #        url: ${JDBC_DATABSE_URL:}
        #        username: ${JDBC_DATABASE_USERNAME:}
        #        password: ${JDBC_DATABASE_PASSWORD:}
        #        driver-class-name: org.postgresql.Driver

        #        This is for local development.
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}?${DATABASE_QSP}
        username: ${DATABASE_ROOT_USER}
        password: ${DATABASE_ROOT_PASS}

    # This setting is used for uploading images to the server
    #  servlet:
    #    multipart:
    #      max-file-size: 15MB
    #      max-request-size: 15MB

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        #       This is for Heroku Cloud
        #        database-platform: org.hibernate.dialect.PostgreSQLDialect

        #       This is for local development
        database-platform: org.hibernate.dialect.MySQL8Dialect

    # This is used for testing purposes
    #    web:
    #      resources:
    #        static-locations: classpath:/static/
    mvc:
        hiddenmethod:
            filter:
                enabled: true

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

database:
    admin-username: ${DATABASE_ADMIN_USER}
    admin-password: ${DATABASE_ADMIN_PASS}

##This is for Heroku Cloud
#server:
#    port: ${PORT:8080}

#This is for local development.
server:
    port: ${APP_PORT}