logging:
    level:
        blog: WARN
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor: TRACE
            nodeValue: WARN
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MY_SQL_HOST}:${MY_SQL_PORT}/${MY_SQL_DB}?${MY_SQL_QSP}
        username: ${MY_SQL_USER}
        password: ${MY_SQL_PASS}
    #  servlet:
    #    multipart:
    #      max-file-size: 15MB
    #      max-request-size: 15MB
    jpa:
        hibernate:
            ddl-auto: create
            #//TODO: change ddl-auto when ready
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#    web:
#      resources:
#        static-locations: classpath:/static
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

server:
    port: ${PORT}

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
